name: Shell Commands

on: [push, pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello World"
      - name: Multi line script
        run: |
          node -v
          npm -v