name: Shell Commands

on: [push, pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multi line script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python 
  windows-commands:
    runs-on: windows-latest
    steps:
      - name: powershell directory
        run:  Get-Location
      - name: linux directory
        run: pwd
        shell: bash 